import org.gradle.internal.os.OperatingSystem

plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

configurations {
    windows_x64
    linux_x64
    macOS_x64
}

repositories {
    maven {
        url "https://www.hec.usace.army.mil/nexus/repository/maven-public/"
    }
    mavenCentral()
}

dependencies {
    implementation 'commons-cli:commons-cli:1.4'
    // HEC-Monolith and its runtime dependencies
    implementation ('mil.army.usace.hec:hec-monolith:3.+') {
        transitive = false
    }
    runtimeOnly 'mil.army.usace.hec:S10hmsPlugin:6.0.0.51'
    runtimeOnly 'mil.army.usace.hec:images:1.0'
    runtimeOnly 'com.google.flogger:flogger:0.7.4'
    runtimeOnly 'com.google.flogger:flogger-system-backend:0.7.4'
    runtimeOnly 'com.vividsolutions:jts:1.13'
    // JavaHeclib
    windows_x64 'mil.army.usace.hec:javaHeclib:7-IU-0-win-x86_64@zip'
    linux_x64 'mil.army.usace.hec:javaHeclib:7-IU-0-linux-x86_64@tar.gz'
    macOS_x64 'mil.army.usace.hec:javaHeclib:7-IU-0-macOS-x86_64-full@zip'
    // JUnit
    testImplementation 'org.junit.jupiter:junit-jupiter:5.4.0'
}

jar {
    from {
        configurations.runtime.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

tasks.register('getNatives', Copy) {
    if (OperatingSystem.current().isWindows()) {
        configurations.windows_x64.asFileTree.each {
            from(zipTree(it))
            into "$projectDir/x64"
        }
    } else if (OperatingSystem.current().isLinux()) {
        configurations.linux_x64.asFileTree.each {
            from(tarTree(it))
            into "$projectDir/x64"
        }
    } else if (OperatingSystem.current().isMacOsX()) {
        configurations.macOS_x64.asFileTree.each {
            from(zipTree(it))
            into "$projectDir/x64"
        }
    }
}

tasks.register('refreshNatives') {
    destroyables.register("$projectDir/x64")
    doLast {
        delete("$projectDir/x64")
    }
    finalizedBy(getNatives)
}

test {
    if (OperatingSystem.current().isWindows()) {
        useJUnitPlatform()
        ignoreFailures = true
        jvmArgs = ["-Djava.library.path=${projectDir}/x64"]
    }
}
